import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './Modules/**/resources/views/**/*.blade.php',
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', 'Figtree', ...defaultTheme.fontFamily.sans],
                'display-lg': ['Inter', ...defaultTheme.fontFamily.sans],
                'mono-data': ['Inter', ...defaultTheme.fontFamily.sans],
                'label-md': ['Inter', ...defaultTheme.fontFamily.sans],
                'headline-lg': ['Inter', ...defaultTheme.fontFamily.sans],
                'headline-lg-mobile': ['Inter', ...defaultTheme.fontFamily.sans],
                'title-md': ['Inter', ...defaultTheme.fontFamily.sans],
                'label-sm': ['Inter', ...defaultTheme.fontFamily.sans],
                'body-lg': ['Inter', ...defaultTheme.fontFamily.sans],
                'body-md': ['Inter', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '700' }],
                'mono-data': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'label-md': ['15px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
                'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' }],
                'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
                'title-md': ['22px', { lineHeight: '30px', fontWeight: '600' }],
                'label-sm': ['13px', { lineHeight: '18px', letterSpacing: '0.05em', fontWeight: '500' }],
                'body-lg': ['20px', { lineHeight: '32px', fontWeight: '400' }],
                'body-md': ['17px', { lineHeight: '26px', fontWeight: '400' }],
            },
            colors: {
                'outline': '#74777e',
                'secondary-fixed-dim': '#94ccff',
                'surface': '#f7f9fc',
                'on-background': '#191c1e',
                'tertiary-fixed-dim': '#f2bb90',
                'surface-container-high': '#e6e8eb',
                'primary-container': '#0a2342',
                'outline-variant': '#c4c6cf',
                'secondary': '#236390',
                'inverse-on-surface': '#eff1f4',
                'surface-bright': '#f7f9fc',
                'surface-container-low': '#f2f4f7',
                'tertiary-container': '#391b00',
                'alert-amber': '#E6930A',
                'on-secondary-container': '#105783',
                'error': '#ba1a1a',
                'surface-container-lowest': '#ffffff',
                'error-container': '#ffdad6',
                'on-primary-fixed': '#021c3a',
                'primary-fixed-dim': '#b2c7ef',
                'tertiary-fixed': '#ffdcc3',
                'tertiary': '#190900',
                'on-secondary-fixed-variant': '#004b74',
                'on-secondary': '#ffffff',
                'on-tertiary': '#ffffff',
                'on-primary-fixed-variant': '#324768',
                'surface-dim': '#d8dadd',
                'on-tertiary-container': '#b08059',
                'secondary-container': '#94ccff',
                'pure-black': '#000000',
                'secondary-fixed': '#cde5ff',
                'inverse-primary': '#b2c7ef',
                'surface-container': '#eceef1',
                'on-tertiary-fixed-variant': '#643e1d',
                'surface-tint': '#4a5f81',
                'primary-fixed': '#d5e3ff',
                'on-secondary-fixed': '#001d32',
                'on-primary': '#ffffff',
                'surface-variant': '#e0e3e6',
                'on-error-container': '#93000a',
                'primary': '#000d22',
                'on-primary-container': '#768baf',
                'on-surface': '#191c1e',
                'surface-container-highest': '#e0e3e6',
                'on-surface-variant': '#44474e',
                'border-gray': '#D1D5DB',
                'inverse-surface': '#2d3133',
                'background': '#f7f9fc',
                'on-tertiary-fixed': '#2e1500',
                'on-error': '#ffffff',
                'critical-red': '#E34120',
            },
            spacing: {
                'section-gap': '96px',
                'stack-md': '16px',
                'stack-sm': '8px',
                'margin-edge': '32px',
                'gutter': '32px',
                'stack-lg': '32px',
            },
            maxWidth: {
                'container-max': '1440px',
            },
        },
    },
    plugins: [forms],
};
